repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        files: \.py$
        args: ["check"]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        files: \.py$
        args: ["--rcfile=.pylintrc"]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
